{
  "error": "Exception encountered when calling Sequential.call().\n\n[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 9, but received input with shape (1, 8)[0m\n\nArguments received by Sequential.call():\n  â€¢ inputs=tf.Tensor(shape=(1, 8), dtype=float32)\n  â€¢ training=False\n  â€¢ mask=None"
}
